/*
Exercise 3: (4) Write a method that creates and initializes a twodimensional array of
double. The size of the array is determined by the arguments of the method, and the
initialization values are a range determined by beginning and ending values that are also
arguments of the method. Create a second method that will print the array generated by the
first method. In main( ) test the methods by creating and printing several different sizes of
arrays.
 */
public class Runner {
    public static double[][] newArray(int rows, int columns) throws IllegalArgumentException{
        int max,min;
        if(rows <= 0 || columns <= 0) {
            throw new IllegalArgumentException();
        }
        else {
            if(rows > columns) {
                max = rows;
                min = columns;
            }
            else {
                max = columns;
                min = rows;
            }
        }
        double[][] arr = new double[rows][columns];
        for(int i = 0; i < rows; i++) {
            for(int j = 0; j < columns; j++) {
                arr[i][j] = Math.random() * (max - min) + min;
            }
        }
        return arr;
    }
    public static void printArray(double[][] arr) {
        for(int i = 0; i < arr.length; i++) {
            for(int j = 0; j < arr[0].length; j++) {
                System.out.print(arr[i][j] + "   ");
            }
            System.out.println();
        }
    }
    public static void main(String[] args) {
        printArray(newArray(5,7));
        System.out.println();
        printArray(newArray(7,7));
    }
}
